[package]
name = "ucabled"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["ble"]
ble = ["dep:bluer"]

[dependencies]
anyhow = "1"
futures = "0.3"
hex = "0.4"
rand = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

p256 = { version = "0.13", features = ["ecdh"] }
hkdf = "0.12"
sha2 = "0.10"
hmac = "0.12"
aes = "0.8"
aes-gcm = "0.10"

tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26", features = [
  "rustls-tls-webpki-roots",
] }
rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "std",
] }
qrcode = { version = "0.14", default-features = false }
eframe = { version = "0.36", default-features = false, features = [
  "default_fonts",
  "wgpu",
  "wayland",
] }

bluer = { version = "0.17", optional = true, features = ["bluetoothd"] }
dbus = "0.9"
dbus-crossroads = "0.5"
libc = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
