import Reveal from "../components/Reveal";

export default function Footer() {
  return (
    <footer className="border-t" style={{ borderColor: "var(--phos-12)" }}>
      <div className="mx-auto max-w-6xl px-5 sm:px-8 py-14">
        <Reveal>
          <p className="glow text-lg sm:text-2xl font-extrabold uppercase" style={{ color: "var(--phos-hi)" }}>
            the machine is only a relay.
          </p>
          <p className="mt-2 text-[13px]" style={{ color: "var(--phos-55)" }}>
            the passkey never leaves the phone.
          </p>
        </Reveal>
        <Reveal delay={100}>
          <div className="mt-10 flex flex-wrap items-center gap-x-8 gap-y-3 text-[11px] uppercase tracking-widest" style={{ color: "var(--phos-40)" }}>
            <a className="hov" href="https://github.com/fuzy112/ucabled" target="_blank" rel="noreferrer">
              github.com/fuzy112/ucabled ↗
            </a>
            <a className="hov" href="https://github.com/fuzy112/ucabled/releases/tag/v0.1.1" target="_blank" rel="noreferrer">
              v0.1.1 — latest release
            </a>
            <span>gpl-3.0-or-later</span>
            <span>rust · tokio · bluez · gtk4</span>
          </div>
          <p className="mt-6 text-[11px]" style={{ color: "var(--phos-25)" }}>
            note: this project is entirely generated by large language models (llms). audit before you trust — like anything else holding a pipe to your passkeys.
          </p>
        </Reveal>
      </div>
    </footer>
  );
}
